jobplus/app.py
'''
注册蓝图、初始化数据库、定义 create_app 函数
'''

from flask import Flask
from flask_migrate import Migrate
from flask_login import LoginManager
from jobplus.config import configs
from jobplus.models import db, User
from jobplus.blueprints import (home_bp, user_bp, company_bp, job_bp, 
                                firm_bp, admin_bp)


def create_app(config):
    app = Flask(__name__)
    app.config.from_object(configs.get(config))
    register_blueprints(app)
    register_extensions(app)
    return app


def register_blueprints(app):
    app.register_blueprint(home_bp)
    app.register_blueprint(user_bp)
    app.register_blueprint(company_bp)
    app.register_blueprint(job_bp)
    app.register_blueprint(firm_bp)
    app.register_blueprint(admin_bp)


def register_extensions(app):
    db.init_app(app)
    Migrate(app, db)
    login_manager = LoginManager()
    login_manager.init_app(app)

    @login_manager.user_loader
    def user_loader(id):
        return User.query.get(id)

    login_manager.login_view = 'front.login'

jobplus/blueprints/__init__.py
from .home import home_bp
from .user import user_bp
from .company import company_bp
from .job import job_bp
from .firm import firm_bp
from .admin import admin_bp

jobplus/blueprints/admin.py
'''
Admin蓝图
'''

from flask import (Blueprint, render_template, flash, redirect, url_for,
                   request, current_app, abort)
from jobplus.decorators import admin_required
from jobplus.models import User, CompanyInfo, Job, db, UserInfo
from jobplus.forms import (CompanyInfoForm, EditCompanyForm, EditJobForm, 
                           AdminEditUserForm, AdminUserInfoForm, 
                           AdminCreateUserForm)


admin_bp = Blueprint('admin', __name__, url_prefix='/admin')

@admin_bp.route('/')
@admin_required
def index():
    return render_template('admin/index.html')

@admin_bp.route('/online-jobs')
@admin_required
def online_jobs():
    page = request.args.get('page', default=1, type=int)
    pagination = Job.query.filter_by(status=Job.ONLINE).paginate(
            page=page,
            per_page=current_app.config['COMPANY_PER_PAGE'],
            error_out=False
        )
    return render_template('admin/online_jobs.html', pagination=pagination)

@admin_bp.route('/offline-jobs')
@admin_required
def offline_jobs():
    page = request.args.get('page', default=1, type=int)
    pagination = Job.query.filter_by(status=Job.OFFLINE).paginate(
            page=page,
            per_page=current_app.config['COMPANY_PER_PAGE'],
            error_out=False
        )
    return render_template('admin/offline_jobs.html', pagination=pagination)

@admin_bp.route('/online/<int:job_id>', methods=['GET', 'POST'])
@admin_required
def online(job_id):
    job = Job.query.get_or_404(job_id)
    job.status = Job.ONLINE
    db.session.add(job)
    db.session.commit()
    return redirect(url_for('.offline_jobs'))

@admin_bp.route('/offline/<int:job_id>', methods=['GET', 'POST'])
@admin_required
def offline(job_id):
    job = Job.query.get_or_404(job_id)
    job.status = Job.OFFLINE
    db.session.add(job)
    db.session.commit()
    return redirect(url_for('.online_jobs'))

@admin_bp.route('/edit-job/<int:job_id>', methods=['GET', 'POST'])
@admin_required
def edit_job(job_id):
    job = Job.query.get_or_404(job_id)
    form = EditJobForm(obj=job)
    if form.validate_on_submit():
        form.update_job(job)
        flash('职位更新成功', 'success')
        return redirect(url_for('.online_jobs'))
    return render_template('admin/edit_job.html', form=form, job=job)

@admin_bp.route('/del-job/<int:job_id>', methods=['GET', 'POST'])
@admin_required
def del_job(job_id):
    job = Job.query.get_or_404(job_id)
    db.session.delete(job)
    db.session.commit()
    flash('职位已删除', 'success')
    return redirect(url_for('.online_jobs'))

@admin_bp.route('/users')
@admin_required
def users():
    page = request.args.get('page', default=1, type=int)
    pagination = User.query.filter_by(role=10).paginate(
            page=page,
            per_page=current_app.config['COMPANY_PER_PAGE'],
            error_out=False
        )
    return render_template('admin/users.html', pagination=pagination)

@admin_bp.route('/edit-user/<int:user_id>', methods=['GET', 'POST'])
@admin_required
def edit_user(user_id):
    user = User.query.get_or_404(user_id)
    form = AdminEditUserForm(obj=user)
    if form.validate_on_submit():
        form.update_user(user)
        flash('用户更新成功', 'success')
        if user.role == 10:
            return redirect(url_for('.users'))
        else:
            return redirect(url_for('.companies'))
    return render_template('admin/edit_user.html', form=form, user=user)
    
@admin_bp.route('/edit-userinfo/<int:user_id>', methods=['GET', 'POST'])
@admin_required
def edit_userinfo(user_id):
    user = User.query.get_or_404(user_id)
    if user.role == 10:
        user_info = user.user_info
        form = AdminUserInfoForm(obj=user_info)
    else:
        abort(404)
    if form.validate_on_submit():
        if user_info:
            form.update_userinfo(user_info, user)
            flash('用户信息更新成功', 'success')
            return redirect(url_for('.users'))
        else:
            user_info = UserInfo()
            form.update_userinfo(user_info, user)
            flash('用户信息更新成功', 'success')
            return redirect(url_for('.users'))
    return render_template('admin/edit_userinfo.html', form=form, user=user)

@admin_bp.route('/del-user/<int:user_id>', methods=['GET', 'POST'])
@admin_required
def del_user(user_id):
    user = User.query.get_or_404(user_id)
    role = user.role
    db.session.delete(user)
    db.session.commit()
    flash('用户已删除', 'success')
    if role == 10:
        return redirect(url_for('.users'))
    elif role == 20:
        return redirect(url_for('.companies'))
    else:
        return redirect(url_for('.users_ban'))

@admin_bp.route('/companies')
@admin_required
def companies():
    page = request.args.get('page', default=1, type=int)
    pagination = User.query.filter_by(role=20).paginate(
            page=page,
            per_page=current_app.config['COMPANY_PER_PAGE'],
            error_out=False
        )
    return render_template('admin/companies.html', pagination=pagination)

@admin_bp.route('/edit-companyinfo/<int:user_id>', methods=['GET', 'POST'])
@admin_required
def edit_companyinfo(user_id):
    user = User.query.get_or_404(user_id)
    if user.role == 20:
        company_info = user.company_info
        form = CompanyInfoForm(obj=company_info)
    else:
        abort(404)
    if form.validate_on_submit():
        if company_info:
            form.update_companyinfo(company_info)
            flash('企业信息更新成功', 'success')
            return redirect(url_for('.companies'))
        else:
            form.create_companyinfo(user)
            flash('企业信息更新成功', 'success')
            return redirect(url_for('.companies'))
    return render_template('admin/edit_companyinfo.html',
                           form=form, user=user)

@admin_bp.route('/ban/<int:user_id>', methods=['GET', 'POST'])
@admin_required
def ban(user_id):
    user = User.query.get_or_404(user_id)
    role = user.role
    if role == 20:
        user.username += 'bc'
    else:
        user.username += 'bu' 
    user.role = 0
    db.session.add(user)
    db.session.commit()
    return redirect(url_for('.users_ban'))

@admin_bp.route('/lift-ban/<int:user_id>', methods=['GET', 'POST'])
@admin_required
def lift_ban(user_id):
    user = User.query.get_or_404(user_id)
    if 'bc' in user.username:
        user.role = 20
        user.username = user.username.replace('bc', '')
    else:
        user.role = 10
        user.username = user.username.replace('bu', '')
    db.session.add(user)
    db.session.commit()
    return redirect(url_for('.users_ban'))

@admin_bp.route('/users-ban')
@admin_required
def users_ban():
    page = request.args.get('page', default=1, type=int)
    pagination = User.query.filter_by(role=0).paginate(
            page=page,
            per_page=current_app.config['COMPANY_PER_PAGE'],
            error_out=False
        )
    return render_template('admin/ban_users.html', pagination=pagination)

@admin_bp.route('/create-user', methods=['GET', 'POST'])
@admin_required
def create_user():
    form = AdminCreateUserForm()
    if form.validate_on_submit():
        form.create_user()
        flash('用户创建成功', 'success')
        return redirect(url_for('.index'))
    return render_template('admin/create_user.html', form=form)
    

jobplus/blueprints/firm.py
'''
Firm蓝图
'''

from flask import (Blueprint, render_template, flash, redirect, url_for,
                   request, current_app, abort)
from jobplus.models import Job, User


firm_bp = Blueprint('firm', __name__, url_prefix='/firms')

@firm_bp.route('/')
def firms():
    page = request.args.get('page', default=1, type=int)
    pagination = User.query.filter_by(role=20).paginate(
            page=page,
            per_page=current_app.config['HOME_PER_PAGE'],
            error_out=False
        )
    return render_template('firms/firms.html', pagination=pagination)

@firm_bp.route('/<int:user_id>')
def detail(user_id):
    firm = User.query.get_or_404(user_id)
    if firm.role != 20:
        abort(404)
    else:
        jobs_num = len(Job.query.filter_by(company_id=firm.id, 
            status=Job.ONLINE).all())
        return render_template('firms/detail.html', firm=firm, jobs_num=jobs_num)

@firm_bp.route('/<int:user_id>/jobs')
def jobs(user_id):
    firm = User.query.get_or_404(user_id)
    if firm.role != 20:
        abort(404)
    else:
        jobs = Job.query.filter_by(company_id=firm.id, status=Job.ONLINE).all()
        return render_template('firms/jobs.html', jobs=jobs, firm=firm)

jobplus/blueprints/home.py
'''
首页蓝图
'''

from flask import (Blueprint, render_template, flash, redirect, url_for,
                   abort)
from flask_login import login_user, logout_user, login_required
from jobplus.models import User, Job, db
from jobplus.forms import LoginForm, UserRegisterForm, CompanyRegisterForm

home_bp = Blueprint('home', __name__)

@home_bp.route('/')
def index():
    jobs = db.session.query(Job).order_by(Job.create_at.desc()).limit(15).all()
    return render_template('index.html', jobs=jobs)

@home_bp.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user.role == 0:
            abort(403)
        else:
            login_user(user, form.remember_me.data)
            return redirect(url_for('.index'))
    '''
    else:
        flash('您的帐户已被封禁', 'danger')
        return redirect(url_for('.login'))
    '''    
    return render_template('login.html', form=form)

@home_bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash('您已退出登录', 'success')
    return redirect(url_for('.index'))

@home_bp.route('/user-register', methods=['GET', 'POST'])
def user_register():
    form = UserRegisterForm()
    if form.validate_on_submit():
        form.create_user()
        flash('注册成功，请登录！', 'success')
        return redirect(url_for('.login'))
    return render_template('user_register.html', form=form)

@home_bp.route('/company-register', methods=['GET', 'POST'])
def company_register():
    form = CompanyRegisterForm()
    if form.validate_on_submit():
        form.create_company()
        flash('注册成功，请登录！', 'success')
        return redirect(url_for('.login'))
    return render_template('company_register.html', form=form)
   

jobplus/blueprints/job.py
'''
Job蓝图
'''

from flask import (Blueprint, render_template, flash, redirect, url_for,
                   request, current_app)
from jobplus.models import Job, SendCV, User
from flask_login import current_user
from jobplus.forms import *


job_bp = Blueprint('job', __name__, url_prefix='/jobs')

@job_bp.route('/')
def jobs():
    page = request.args.get('page', default=1, type=int)
    pagination = Job.query.filter_by(status=Job.ONLINE).paginate(
            page=page,
            per_page=current_app.config['HOME_PER_PAGE'],
            error_out=False
        )
    return render_template('jobs/jobs.html', pagination=pagination)

@job_bp.route('/<int:job_id>')
def job_detail(job_id):
    #job = Job.query.get_or_404(job_id)
    job = Job.query.filter_by(id=job_id, status=Job.ONLINE).first_or_404()
    sendcv = SendCV()
    if current_user.is_authenticated:
        user = User.query.filter_by(id=current_user.id).first()
        return render_template('jobs/detail.html', job=job, 
                                sendcv=sendcv, user=user)
    else:
        return render_template('jobs/detail.html', job=job)

jobplus/blueprints/resume.py
from flask import Blueprint, render_template, flash, redirect, url_for
from flask_login import current_user
from jobplus.models import Resume, User


resume_bp = Blueprint('resume', __name__, url_prefix='/resume')

@resume_bp.route('/send-resume')
def send_resume()

jobplus/blueprints/user.py
'''
用户蓝图
'''

from flask import (Blueprint, render_template, flash, redirect, 
                   url_for, abort, request, current_app)
from flask_login import current_user
from jobplus.decorators import user_required
from jobplus.models import User, UserInfo, SendCV, Job, db
from jobplus.forms import UserInfoForm, EditUserForm


user_bp = Blueprint('user', __name__, url_prefix='/user')

@user_bp.route('/')
@user_required
def index():
    return render_template('user/index.html')

@user_bp.route('/info')
@user_required
def userinfo():
    user = User.query.filter_by(username=current_user.username).first()
    return render_template('user/user_info.html', user=user)

@user_bp.route('/edit-userinfo', methods=['GET', 'POST'])
@user_required
def edit_userinfo():
    user = User.query.filter_by(username=current_user.username).first()
    user_info = user.user_info
    form = UserInfoForm(obj=user_info)
    if not user_info:
        if form.validate_on_submit():
            form.create_userinfo(user)
            flash('信息更新成功！', 'success')
            return redirect(url_for('.index'))
    else:
        if form.validate_on_submit():
            form.update_userinfo(user_info)
            flash('信息更新成功！', 'success')
            return redirect(url_for('.index'))
    return render_template('user/edit_userinfo.html', form=form)

@user_bp.route('/edit-user', methods=['GET', 'POST'])
@user_required
def edit_user():
    user = User.query.filter_by(username=current_user.username).first()
    form = EditUserForm(obj=user)
    if form.validate_on_submit():
        form.update_user(user)
        flash('信息更新成功！', 'success')
        return redirect(url_for('.index'))
    return render_template('user/edit_user.html', form=form)
        
@user_bp.route('/send-cv/<int:job_id>/<int:company_id>', methods=['GET', 'POST'])
@user_required
def send_cv(job_id, company_id):
    job = Job.query.filter_by(id=job_id).first_or_404()
    user = User.query.filter_by(username=current_user.username).first()
    company = User.query.filter_by(id=company_id).first()
    send_cv = SendCV() 
    send_cv.sender = user
    send_cv.job = job
    send_cv.receiver = company
    db.session.add(send_cv)
    db.session.commit()
    flash('简历投递成功！', 'success')
    return redirect(url_for('job.job_detail', job_id=job.id))
    
@user_bp.route('/sent-cv')
@user_required
def sent_cv():
    page = request.args.get('page', default=1, type=int)
    pagination = SendCV.query.filter_by(
            sender_id=current_user.id).paginate(
                page=page,
                per_page=current_app.config['COMPANY_PER_PAGE'],
                error_out=False
        )
    return render_template('user/sent_cv.html', 
            pagination=pagination)

@user_bp.route('/del-cv/<int:job_id>', methods=['GET', 'POST'])
@user_required
def del_cv(job_id):
    send_cv = SendCV.query.filter_by(job_id=job_id, 
            sender_id=current_user.id).first_or_404()
    db.session.delete(send_cv)
    db.session.commit()
    return redirect(url_for('.sent_cv'))

@user_bp.route('/unread-cv')
@user_required
def unread_cv():
    page = request.args.get('page', default=1, type=int)
    pagination = SendCV.query.filter_by(
            sender_id=current_user.id, status=10).paginate(
                page=page,
                per_page=current_app.config['COMPANY_PER_PAGE'],
                error_out=False
        )
    return render_template('user/unread_cv.html', 
            pagination=pagination)

@user_bp.route('/accept-cv')
@user_required
def accept_cv():
    page = request.args.get('page', default=1, type=int)
    pagination = SendCV.query.filter_by(
            sender_id=current_user.id, status=30).paginate(
                page=page,
                per_page=current_app.config['COMPANY_PER_PAGE'],
                error_out=False
        )
    return render_template('user/accept_cv.html', 
            pagination=pagination)

@user_bp.route('/refuse-cv')
@user_required
def refuse_cv():
    page = request.args.get('page', default=1, type=int)
    pagination = SendCV.query.filter_by(
            sender_id=current_user.id, status=20).paginate(
                page=page,
                per_page=current_app.config['COMPANY_PER_PAGE'],
                error_out=False
        )
    return render_template('user/refuse_cv.html', 
            pagination=pagination)

jobplus/templates/user/accept_cv.html
{% extends "user/index.html" %}
{% from "macros.html" import render_pagination %}

{% block title %}Accept-CV{% endblock %}

{% block user %}
<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link" href="{{ url_for('user.sent_cv') }}">全部已投</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{{ url_for('user.unread_cv') }}">未读</a>
  </li>
  <li class="nav-item">
    <a class="nav-link active" href="#">已接受</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{{ url_for('user.refuse_cv') }}">已拒绝</a>
  </li>
</ul>
<table class="table">
  <thead>
    <tr>
      <th>职位</th>
      <th>企业名</th>
      <th>状态</th>
    </tr>
    <tbody>
      {% for cv in pagination.items %}
      <tr>
        <td>
          <a href="{{ url_for('job.job_detail', job_id=cv.job.id) }}" 
             class="btn btn-light" role="button" 
             aria-pressed="true">{{ cv.job.title }}</a>
        </td>
        <td>{{ cv.job.company.username }}</td>
        {% if cv.status == 30 %}
        <td>已接受</td>
        {% endif %}
      </tr>
      {% endfor %}
    </tbody>
  </thead>
</table>
{{ render_pagination(pagination, 'user.unread_cv') }}
{% endblock %}

jobplus/templates/user/edit_user.html
{% extends "user/index.html" %}
{% from "macros.html" import render_form %}

{% block title %}EditUser{% endblock %}

{% block user %}
<div class="form">
  <h2>修改帐户信息</h2>
  {{ render_form(form, url_for('user.edit_user')) }}
</div>
{% endblock %}

jobplus/templates/user/edit_userinfo.html
{% extends "user/index.html" %}
{% from "macros.html" import render_form %}

{% block title %}EditUserInfo{% endblock %}

{% block user %}
<div class="form">
  <h2>修改个人信息</h2>
  {{ render_form(form, url_for('user.edit_userinfo')) }}
</div>
{% endblock %}

jobplus/templates/user/index.html
{% extends "base.html" %}

{% block title %}UserInfo{% endblock %}

{% block body%}
<div class="row">
  <div class="col-md-3">
    <h4>管理</h4>
    <div class="list-group">
      <a href="{{ url_for('user.userinfo') }}"
         class="list-group-item list-group-action list-group-item-light">
         个人信息</a>
      <a href="{{ url_for('user.sent_cv') }}"
         class="list-group-item list-group-action list-group-item-light">
         已投简历</a>
     </div>
   </div>
   <div class="col-md-9">
   {% block user %}{% endblock %}
</div>
{% endblock %}

jobplus/templates/user/refuse_cv.html
{% extends "user/index.html" %}
{% from "macros.html" import render_pagination %}

{% block title %}Refuse-CV{% endblock %}

{% block user %}
<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link" href="{{ url_for('user.sent_cv') }}">全部已投</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{{ url_for('user.unread_cv') }}">未读</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{{ url_for('user.accept_cv') }}">已接受</a>
  </li>
  <li class="nav-item">
    <a class="nav-link active" href="#">已拒绝</a>
  </li>
</ul>
<table class="table">
  <thead>
    <tr>
      <th>职位</th>
      <th>企业名</th>
      <th>状态</th>
    </tr>
    <tbody>
      {% for cv in pagination.items %}
      <tr>
        <td>
          <a href="{{ url_for('job.job_detail', job_id=cv.job.id) }}" 
             class="btn btn-light" role="button" 
             aria-pressed="true">{{ cv.job.title }}</a>
        </td>
        <td>{{ cv.job.company.username }}</td>
        {% if cv.status == 20 %}
        <td>已拒绝</td>
        {% endif %}
      </tr>
      {% endfor %}
    </tbody>
  </thead>
</table>
{{ render_pagination(pagination, 'user.unread_cv') }}
{% endblock %}

jobplus/templates/user/sent_cv.html
{% extends "user/index.html" %}
{% from "macros.html" import render_pagination %}

{% block title %}Sent-CV{% endblock %}

{% block user %}
<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link active" href="#">全部已投</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{{ url_for('user.unread_cv') }}">未读</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{{ url_for('user.accept_cv') }}">已接受</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{{ url_for('user.refuse_cv') }}">已拒绝</a>
  </li>
</ul>
<table class="table">
  <thead>
    <tr>
      <th>职位</th>
      <th>企业名</th>
      <th>状态</th>
      <th>操作</th>
    </tr>
    <tbody>
      {% for cv in pagination.items %}
      <tr>
        <td>
          <a href="{{ url_for('job.job_detail', job_id=cv.job.id) }}" 
             class="btn btn-light" role="button" 
             aria-pressed="true">{{ cv.job.title }}</a>
        </td>
        <td>{{ cv.job.company.username }}</td>
        {% if cv.status == 10 %}
        <td>未读</td>
        {% elif cv.status == 20 %}
        <td>已拒绝</td>
        {% else %}
        <td>已接受</td>
        {% endif %}
        <td>
          <div class="btn-group">
            {% if cv.status == 10 %}
            <button class="btn btn-secondary btn-sm dropdown-toggle" 
                    type="button" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
               操作
            </button>
            <div class="dropdown-menu">
               <a class="dropdown-item" 
                  href="{{ url_for('user.del_cv', job_id=cv.job.id) }}">删除</a>
            </div>
            {% else %}
            <button type="button" class="btn btn-outline-dark" 
                    disabled>企业已处理无法操作</button>
            {% endif %}
          </div>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </thead>
</table>
{{ render_pagination(pagination, 'user.sent_cv') }}
{% endblock %}

jobplus/templates/user/unread_cv.html
{% extends "user/index.html" %}
{% from "macros.html" import render_pagination %}

{% block title %}Unread-CV{% endblock %}

{% block user %}
<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link" href="{{ url_for('user.sent_cv') }}">全部已投</a>
  </li>
  <li class="nav-item">
    <a class="nav-link active" href="#">未读</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{{ url_for('user.accept_cv') }}">已接受</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{{ url_for('user.refuse_cv') }}">已拒绝</a>
  </li>
</ul>
<table class="table">
  <thead>
    <tr>
      <th>职位</th>
      <th>企业名</th>
      <th>状态</th>
      <th>操作</th>
    </tr>
    <tbody>
      {% for cv in pagination.items %}
      <tr>
        <td>
          <a href="{{ url_for('job.job_detail', job_id=cv.job.id) }}" 
             class="btn btn-light" role="button" 
             aria-pressed="true">{{ cv.job.title }}</a>
        </td>
        <td>{{ cv.job.company.username }}</td>
        {% if cv.status == 10 %}
        <td>未读</td>
        {% endif %}
        <td>
          <div class="btn-group">
            {% if cv.status == 10 %}
            <button class="btn btn-secondary btn-sm dropdown-toggle" 
                    type="button" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
               操作
            </button>
            <div class="dropdown-menu">
               <a class="dropdown-item" 
                  href="{{ url_for('user.del_cv', job_id=cv.job.id) }}">删除</a>
            </div>
            {% endif %}
          </div>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </thead>
</table>
{{ render_pagination(pagination, 'user.unread_cv') }}
{% endblock %}

jobplus/templates/user/user_info.html
{% extends "user/index.html" %}

{% block title %}User-Info{% endblock %}

{% block user %}
<div class="card text-center">
  <div class="card-header">
    个人信息一览
  </div>
  <div class="card-body">
    <h5 class="card-title">{{ user.user_info.name }}</h5>
    <p class="card-text">邮箱：{{ user.email }}</p>
    <p class="card-text">手机号：{{ user.user_info.phone_number }}</p> 
    <p class="card-text">工作年限：{{ user.user_info.experience }}</p>
    <p class="card-text">简历地址：{{ user.user_info.resume }}</p>
    <a href="{{ url_for('user.edit_userinfo') }}" class="btn btn-primary">编辑个人信息</a>
    <a href="{{ url_for('user.edit_user') }}" class="btn btn-primary">编辑帐户信息</a>
  </div>
</div>
</div>
{% endblock %}