jobplus/blueprints/admin.py
'''
Admin蓝图
'''

from flask import (Blueprint, render_template, flash, redirect, url_for,
                   request, current_app, abort)
from jobplus.decorators import admin_required
from jobplus.models import User, CompanyInfo, Job, db, UserInfo
from jobplus.forms import (CompanyInfoForm, EditCompanyForm, EditJobForm, 
                           AdminEditUserForm, AdminUserInfoForm, 
                           AdminCreateUserForm)


admin_bp = Blueprint('admin', __name__, url_prefix='/admin')

@admin_bp.route('/')
@admin_required
def index():
    return render_template('admin/index.html')

@admin_bp.route('/online-jobs')
@admin_required
def online_jobs():
    page = request.args.get('page', default=1, type=int)
    pagination = Job.query.filter_by(status=Job.ONLINE).paginate(
            page=page,
            per_page=current_app.config['COMPANY_PER_PAGE'],
            error_out=False
        )
    return render_template('admin/online_jobs.html', pagination=pagination)

@admin_bp.route('/offline-jobs')
@admin_required
def offline_jobs():
    page = request.args.get('page', default=1, type=int)
    pagination = Job.query.filter_by(status=Job.OFFLINE).paginate(
            page=page,
            per_page=current_app.config['COMPANY_PER_PAGE'],
            error_out=False
        )
    return render_template('admin/offline_jobs.html', pagination=pagination)

@admin_bp.route('/online/<int:job_id>', methods=['GET', 'POST'])
@admin_required
def online(job_id):
    job = Job.query.get_or_404(job_id)
    job.status = Job.ONLINE
    db.session.add(job)
    db.session.commit()
    return redirect(url_for('.offline_jobs'))

@admin_bp.route('/offline/<int:job_id>', methods=['GET', 'POST'])
@admin_required
def offline(job_id):
    job = Job.query.get_or_404(job_id)
    job.status = Job.OFFLINE
    db.session.add(job)
    db.session.commit()
    return redirect(url_for('.online_jobs'))

@admin_bp.route('/edit-job/<int:job_id>', methods=['GET', 'POST'])
@admin_required
def edit_job(job_id):
    job = Job.query.get_or_404(job_id)
    form = EditJobForm(obj=job)
    if form.validate_on_submit():
        form.update_job(job)
        flash('职位更新成功', 'success')
        return redirect(url_for('.online_jobs'))
    return render_template('admin/edit_job.html', form=form, job=job)

@admin_bp.route('/del-job/<int:job_id>', methods=['GET', 'POST'])
@admin_required
def del_job(job_id):
    job = Job.query.get_or_404(job_id)
    db.session.delete(job)
    db.session.commit()
    flash('职位已删除', 'success')
    return redirect(url_for('.online_jobs'))

@admin_bp.route('/users')
@admin_required
def users():
    page = request.args.get('page', default=1, type=int)
    pagination = User.query.filter_by(role=10).paginate(
            page=page,
            per_page=current_app.config['COMPANY_PER_PAGE'],
            error_out=False
        )
    return render_template('admin/users.html', pagination=pagination)

@admin_bp.route('/edit-user/<int:user_id>', methods=['GET', 'POST'])
@admin_required
def edit_user(user_id):
    user = User.query.get_or_404(user_id)
    form = AdminEditUserForm(obj=user)
    if form.validate_on_submit():
        form.update_user(user)
        flash('用户更新成功', 'success')
        if user.role == 10:
            return redirect(url_for('.users'))
        else:
            return redirect(url_for('.companies'))
    return render_template('admin/edit_user.html', form=form, user=user)
    
@admin_bp.route('/edit-userinfo/<int:user_id>', methods=['GET', 'POST'])
@admin_required
def edit_userinfo(user_id):
    user = User.query.get_or_404(user_id)
    if user.role == 10:
        user_info = user.user_info
        form = AdminUserInfoForm(obj=user_info)
    else:
        abort(404)
    if form.validate_on_submit():
        if user_info:
            form.update_userinfo(user_info, user)
            flash('用户信息更新成功', 'success')
            return redirect(url_for('.users'))
        else:
            user_info = UserInfo()
            form.update_userinfo(user_info, user)
            flash('用户信息更新成功', 'success')
            return redirect(url_for('.users'))
    return render_template('admin/edit_userinfo.html', form=form, user=user)

@admin_bp.route('/del-user/<int:user_id>', methods=['GET', 'POST'])
@admin_required
def del_user(user_id):
    user = User.query.get_or_404(user_id)
    role = user.role
    db.session.delete(user)
    db.session.commit()
    flash('用户已删除', 'success')
    if role == 10:
        return redirect(url_for('.users'))
    elif role == 20:
        return redirect(url_for('.companies'))
    else:
        return redirect(url_for('.users_ban'))

@admin_bp.route('/companies')
@admin_required
def companies():
    page = request.args.get('page', default=1, type=int)
    pagination = User.query.filter_by(role=20).paginate(
            page=page,
            per_page=current_app.config['COMPANY_PER_PAGE'],
            error_out=False
        )
    return render_template('admin/companies.html', pagination=pagination)

@admin_bp.route('/edit-companyinfo/<int:user_id>', methods=['GET', 'POST'])
@admin_required
def edit_companyinfo(user_id):
    user = User.query.get_or_404(user_id)
    if user.role == 20:
        company_info = user.company_info
        form = CompanyInfoForm(obj=company_info)
    else:
        abort(404)
    if form.validate_on_submit():
        if company_info:
            form.update_companyinfo(company_info)
            flash('企业信息更新成功', 'success')
            return redirect(url_for('.companies'))
        else:
            form.create_companyinfo(user)
            flash('企业信息更新成功', 'success')
            return redirect(url_for('.companies'))
    return render_template('admin/edit_companyinfo.html',
                           form=form, user=user)

@admin_bp.route('/ban/<int:user_id>', methods=['GET', 'POST'])
@admin_required
def ban(user_id):
    user = User.query.get_or_404(user_id)
    role = user.role
    if role == 20:
        user.username += 'bc'
    else:
        user.username += 'bu' 
    user.role = 0
    db.session.add(user)
    db.session.commit()
    return redirect(url_for('.users_ban'))

@admin_bp.route('/lift-ban/<int:user_id>', methods=['GET', 'POST'])
@admin_required
def lift_ban(user_id):
    user = User.query.get_or_404(user_id)
    if 'bc' in user.username:
        user.role = 20
        user.username = user.username.replace('bc', '')
    else:
        user.role = 10
        user.username = user.username.replace('bu', '')
    db.session.add(user)
    db.session.commit()
    return redirect(url_for('.users_ban'))

@admin_bp.route('/users-ban')
@admin_required
def users_ban():
    page = request.args.get('page', default=1, type=int)
    pagination = User.query.filter_by(role=0).paginate(
            page=page,
            per_page=current_app.config['COMPANY_PER_PAGE'],
            error_out=False
        )
    return render_template('admin/ban_users.html', pagination=pagination)

@admin_bp.route('/create-user', methods=['GET', 'POST'])
@admin_required
def create_user():
    form = AdminCreateUserForm()
    if form.validate_on_submit():
        form.create_user()
        flash('用户创建成功', 'success')
        return redirect(url_for('.index'))
    return render_template('admin/create_user.html', form=form)
    

jobplus/blueprints/company.py
'''
企业蓝图
'''

from flask import (Blueprint, render_template, flash, redirect, url_for,
                   request, current_app, abort, g)
from flask_login import current_user
from jobplus.decorators import company_required
from jobplus.models import User, CompanyInfo, Job, db, SendCV
from jobplus.forms import CompanyInfoForm, EditCompanyForm, PostJobForm, EditJobForm
from jobplus.libs.helper import count_unread


company_bp = Blueprint('company', __name__, url_prefix='/company')

@company_bp.route('/')
@company_required
def index():
    unread_num = count_unread() 
    return render_template('company/index.html', unread_num=unread_num)

@company_bp.route('/info')
@company_required
def company_info():
    user = User.query.filter_by(username=current_user.username).first()
    unread_num = count_unread() 
    return render_template('company/company_info.html', user=user, 
                           unread_num=unread_num)

@company_bp.route('/edit-companyinfo', methods=['GET', 'POST'])
@company_required
def edit_companyinfo():
    user = User.query.filter_by(username=current_user.username).first()
    company_info = user.company_info
    form = CompanyInfoForm(obj=company_info)
    if not company_info:
        if form.validate_on_submit():
            form.create_companyinfo(user)
            flash('信息更新成功！', 'success')
            return redirect(url_for('.company_info'))
    else:
        if form.validate_on_submit():
            form.update_companyinfo(company_info)
            flash('信息更新成功！', 'success')
            return redirect(url_for('.company_info'))
    return render_template('company/edit_companyinfo.html', form=form)

@company_bp.route('/edit-company', methods=['GET', 'POST'])
@company_required
def edit_company():
    user = User.query.filter_by(username=current_user.username).first()
    form = EditCompanyForm(obj=user)
    if form.validate_on_submit():
        form.update_user(user)
        flash('信息更新成功！', 'success')
        return redirect(url_for('.company_info'))
    return render_template('company/edit_company.html', form=form)
        
@company_bp.route('/post-job', methods=['GET', 'POST'])
@company_required
def post_job():
    form = PostJobForm()
    unread_num = count_unread() 
    if form.validate_on_submit():
        form.create_job()
        flash('职位发布成功！', 'success')
        return redirect(url_for('.online_jobs'))
    return render_template('company/post_job.html', form=form, unread_num=unread_num)

@company_bp.route('/online-jobs')
@company_required
def online_jobs():
    user = User.query.filter_by(username=current_user.username).first()
    page = request.args.get('page', default=1, type=int)
    pagination = Job.query.with_parent(user).filter_by(status=Job.ONLINE).paginate(
                page=page,
                per_page=current_app.config['COMPANY_PER_PAGE'],
                error_out=False
        )
    unread_num = count_unread() 
    return render_template('company/online_jobs.html', pagination=pagination, 
                           unread_num=unread_num)

@company_bp.route('/offline-jobs')
@company_required
def offline_jobs():
    user = User.query.filter_by(username=current_user.username).first()
    page = request.args.get('page', default=1, type=int)
    pagination = Job.query.with_parent(user).filter_by(status=Job.OFFLINE).paginate(
                page=page,
                per_page=current_app.config['COMPANY_PER_PAGE'],
                error_out=False
        )
    unread_num = count_unread() 
    return render_template('company/offline_jobs.html', pagination=pagination, 
                           unread_num=unread_num)

@company_bp.route('/online/<int:job_id>', methods=['GET', 'POST'])
@company_required
def online(job_id):
    job = Job.query.get_or_404(job_id)
    job.status = Job.ONLINE
    db.session.add(job)
    db.session.commit()
    return redirect(url_for('.offline_jobs'))

@company_bp.route('/offline/<int:job_id>', methods=['GET', 'POST'])
@company_required
def offline(job_id):
    job = Job.query.get_or_404(job_id)
    job.status = Job.OFFLINE
    db.session.add(job)
    db.session.commit()
    return redirect(url_for('.online_jobs'))

@company_bp.route('/edit-job/<int:job_id>', methods=['GET', 'POST'])
@company_required
def edit_job(job_id):
    job = Job.query.get_or_404(job_id)
    if job.company.username == current_user.username:
        form = EditJobForm(obj=job)
        if form.validate_on_submit():
            form.update_job(job)
            flash('职位更新成功', 'success')
            return redirect(url_for('.index'))
    else:
        abort(404)
    unread_num = count_unread() 
    return render_template('company/edit_job.html', form=form, job=job, 
                            unread_num=unread_num)

@company_bp.route('/del-job/<int:job_id>', methods=['GET', 'POST'])
@company_required
def del_job(job_id):
    job = Job.query.get_or_404(job_id)
    if job.company.username == current_user.username:
        db.session.delete(job)
        db.session.commit()
        flash('职位已删除', 'success')
        return redirect(url_for('.index'))
    else:
        abort(404)

@company_bp.route('/unread-cv')
@company_required
def unread_cv():
    page = request.args.get('page', default=1, type=int)
    pagination = SendCV.query.filter_by(
            receiver_id=current_user.id, status=10).paginate(
                page=page,
                per_page=current_app.config['COMPANY_PER_PAGE'],
                error_out=False
        )
    unread_num = count_unread() 
    return render_template('company/unread_cv.html', pagination=pagination, 
                            unread_num=unread_num)

@company_bp.route('/accept-cv')
@company_required
def accept_cv():
    page = request.args.get('page', default=1, type=int)
    pagination = SendCV.query.filter_by(
            receiver_id=current_user.id, status=30).paginate(
                page=page,
                per_page=current_app.config['COMPANY_PER_PAGE'],
                error_out=False
        )
    unread_num = count_unread() 
    return render_template('company/accept_cv.html', pagination=pagination,  
                            unread_num=unread_num)

@company_bp.route('/refuse-cv')
@company_required
def refuse_cv():
    page = request.args.get('page', default=1, type=int)
    pagination = SendCV.query.filter_by(
            receiver_id=current_user.id, status=20).paginate(
                page=page,
                per_page=current_app.config['COMPANY_PER_PAGE'],
                error_out=False
        )
    unread_num = count_unread() 
    return render_template('company/refuse_cv.html', pagination=pagination, 
                            unread_num=unread_num)

@company_bp.route('/refuse/<int:job_id>/<int:user_id>', methods=['GET', 'POST'])
@company_required
def refuse(job_id, user_id):
    send_cv = SendCV.query.filter_by(job_id=job_id, sender_id=user_id).first_or_404()
    send_cv.status = 20
    db.session.add(send_cv)
    db.session.commit()
    return redirect(url_for('.unread_cv'))

@company_bp.route('/accept/<int:job_id>/<int:user_id>', methods=['GET', 'POST'])
@company_required
def accept(job_id, user_id):
    send_cv = SendCV.query.filter_by(job_id=job_id, sender_id=user_id).first_or_404()
    send_cv.status = 30
    db.session.add(send_cv)
    db.session.commit()
    flash('已接受该简历，快去联系求职者面试吧！', 'success')
    return redirect(url_for('.accept_cv'))

jobplus/blueprints/firm.py
'''
Firm蓝图
'''

from flask import (Blueprint, render_template, flash, redirect, url_for,
                   request, current_app, abort)
from jobplus.models import Job, User


firm_bp = Blueprint('firm', __name__, url_prefix='/firms')

@firm_bp.route('/')
def firms():
    page = request.args.get('page', default=1, type=int)
    pagination = User.query.filter_by(role=20).paginate(
            page=page,
            per_page=current_app.config['HOME_PER_PAGE'],
            error_out=False
        )
    return render_template('firms/firms.html', pagination=pagination)

@firm_bp.route('/<int:user_id>')
def detail(user_id):
    firm = User.query.get_or_404(user_id)
    if firm.role != 20:
        abort(404)
    else:
        jobs_num = len(Job.query.filter_by(company_id=firm.id, 
            status=Job.ONLINE).all())
        return render_template('firms/detail.html', firm=firm, jobs_num=jobs_num)

@firm_bp.route('/<int:user_id>/jobs')
def jobs(user_id):
    firm = User.query.get_or_404(user_id)
    if firm.role != 20:
        abort(404)
    else:
        jobs = Job.query.filter_by(company_id=firm.id, status=Job.ONLINE).all()
        return render_template('firms/jobs.html', jobs=jobs, firm=firm)

jobplus/blueprints/home.py
'''
首页蓝图
'''

from flask import (Blueprint, render_template, flash, redirect, url_for,
                   abort)
from flask_login import login_user, logout_user, login_required
from jobplus.models import User, Job, db
from jobplus.forms import LoginForm, UserRegisterForm, CompanyRegisterForm

home_bp = Blueprint('home', __name__)

@home_bp.route('/')
def index():
    jobs = db.session.query(Job).order_by(Job.create_at.desc()).limit(15).all()
    return render_template('index.html', jobs=jobs)

@home_bp.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user.role == 0:
            abort(403)
        else:
            login_user(user, form.remember_me.data)
            return redirect(url_for('.index'))
    '''
    else:
        flash('您的帐户已被封禁', 'danger')
        return redirect(url_for('.login'))
    '''    
    return render_template('login.html', form=form)

@home_bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash('您已退出登录', 'success')
    return redirect(url_for('.index'))

@home_bp.route('/user-register', methods=['GET', 'POST'])
def user_register():
    form = UserRegisterForm()
    if form.validate_on_submit():
        form.create_user()
        flash('注册成功，请登录！', 'success')
        return redirect(url_for('.login'))
    return render_template('user_register.html', form=form)

@home_bp.route('/company-register', methods=['GET', 'POST'])
def company_register():
    form = CompanyRegisterForm()
    if form.validate_on_submit():
        form.create_company()
        flash('注册成功，请登录！', 'success')
        return redirect(url_for('.login'))
    return render_template('company_register.html', form=form)
   

jobplus/templates/base.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}{% endblock %}</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
  {% block css %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">
  {% endblock %}
</head>
<body>
  <!--导航栏-->
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <a class="navbar-brand" href="/">JobPlus</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" 
              data-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent"
              aria-expanded="false"
              aria-label="Toggle navigation">
        <span class="navbor-toggle-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
          <a class="nav-link" href="{{ url_for('job.jobs') }}">职位<span 
                                class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
          <a class="nav-link" href="{{ url_for('firm.firms') }}">公司<span 
                                class="sr-only">(current)</span></a>
          </li>
          {% if current_user.is_authenticated and current_user.is_admin %}
          <li class="nav-item active">
          <a class="nav-link" href="{{ url_for('admin.index') }}">控制台<span 
                                class="sr-only">(current)</span></a>
          </li>
          {% endif %}
        </ul>
        <ul class="nav navbar-nav navbar-right">
          {% if not current_user.is_authenticated %}
            <li><a class="nav-link" 
                   href="{{ url_for('home.user_register') }}">
                   个人用户注册</a></li>
               <li><a class="nav-link" 
                   href="{{ url_for('home.company_register') }}">
                   企业用户注册</a></li>
          <li><a class="nav-link" 
                   href="{{ url_for('home.login') }}">
                   登录</a></li>
          {% elif current_user.is_authenticated and current_user.is_company %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" 
                 id="navbarDropdown" role="button" data-toggle="dropdown"
                 aria-haspopup="true"
                 aria-expanded="false">
                 {{ current_user.username }}
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" 
                   href="{{ url_for('company.index') }}">公司首页</a>
                <div class="dropdown-divider"></div>
                  <a class="dropdown-item" 
                     href="{{ url_for('home.logout') }}">退出登录</a>
              </div>
             </li>
           {% else %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" 
                 id="navbarDropdown" role="button" data-toggle="dropdown"
                 aria-haspopup="true"
                 aria-expanded="false">
                 {{ current_user.username }}
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{{ url_for('user.index') }}">
                   个人首页</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{{ url_for('home.logout') }}">
                   退出登录</a>
              </div>
             </li>
           {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  <div class="container">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for categroy, message in messages %}
    <div class="alert alert-{{ categroy }}" role="alert">
      {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}
    <br>
    {% block body %}{% endblock %}
    {% block fotter %}{% endblock %}
  </div>
  {% block js %}
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  {% endblock %}
</body>
</html>
          

jobplus/templates/companies.html
{% extends "base.html" %}
{% from "macros.html" import render_pagination %}

{% block title %}Jobs{% endblock %}

{% block body%}
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">JOBPLUS</h1>
    <p class="lead">Birth with destiny, Death with Dignity.</p>
  </div>
</div>
<div class="card-columns">
  {% for company in pagination.items %}
    <div class="card bg-light mb-3" style="max-width: 18rem;">
      <div class="card-body">
        <div class="media">
          <a href="#">
            <img src="{{ company.company_info.logo }}" class="mr-3" width="64" height="64" alt="{{ company.username }}">
            <div class="media-body">
              <p class="mt-0">{{ company.username }}</p>
          </a>
              <p class="mt-0">
              {{ company.company_info.address }}
                <a href="{{ company.company_info.website }}">
              企业官网</p>
                </a>
            </div>
        </div>
        {% for domain in company.company_info.domain.split() %}
          <span class="badge badge-pill badge-info">{{ domain }}</span>
        {% endfor %}
      </div>
        <div class="card-footer">
          <center>
            <p>{{ company.company_info.intro }}</p>
            <p>再招职位：
            <a href="#">
            {{ company.publish_job|length }}</p>
            </a>
          </center>
        </div>
    </div>
  {% endfor %}
</div>
{{ render_pagination(pagination, 'home.companies') }}
{% endblock %}

jobplus/templates/jobs.html
{% extends "base.html" %}
{% from "macros.html" import render_pagination %}

{% block title %}Jobs{% endblock %}

{% block body%}
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">JOBPLUS</h1>
    <p class="lead">Birth with destiny, Death with Dignity.</p>
  </div>
</div>
<div class="card-columns">
  {% for job in pagination.items %}
    <div class="card bg-light mb-3" style="max-width: 18rem;">
      <div class="card-body">
        <a href="#">
        <h5 class="card-title">{{ job.title }}</h5>
        </a>
        <p class="card-text">
          {{ job.salary_lower }}k-{{ job.salary_upper }}k
          {% if job.experience_lower == 0 %}
          经验不限
          {% else %}
          {{ job.experience_lower }}-{{ job.experience_upper }}年
          {% endif %}
        </p>
        <p class="card-text">
          {{ job.education }}
          {{ job.company.company_info.address }}
        </p>
        {% for tag in job.tags.split() %}
        <span class="badge badge-pill badge-info">{{ tag }}</span>
        {% endfor %}
      </div>
      <div class="card-footer">
        <div class="media">
            <a href="#">
            <img src="{{ job.company.company_info.logo }}" class="mr-3" width="64" height="64" alt="{{ job.company.username }}">
          <div class="media-body">
            <p class="mt-0">{{ job.company.username }}</p>
            </a>
            <small class="text-muted">{{ job.create_at }}</small>
          </div>
        </div>
      </div>
    </div>
  {% endfor %}
</div>
{{ render_pagination(pagination, 'home.jobs') }}
{% endblock %}