jobplus/app.py
'''
注册蓝图、初始化数据库、定义 create_app 函数
'''

from flask import Flask
from flask_migrate import Migrate
from flask_login import LoginManager
from jobplus.config import configs
from jobplus.models import db, User
from jobplus.blueprints import (home_bp, user_bp, company_bp, job_bp, 
                                firm_bp, admin_bp)


def create_app(config):
    app = Flask(__name__)
    app.config.from_object(configs.get(config))
    register_blueprints(app)
    register_extensions(app)
    return app


def register_blueprints(app):
    app.register_blueprint(home_bp)
    app.register_blueprint(user_bp)
    app.register_blueprint(company_bp)
    app.register_blueprint(job_bp)
    app.register_blueprint(firm_bp)
    app.register_blueprint(admin_bp)


def register_extensions(app):
    db.init_app(app)
    Migrate(app, db)
    login_manager = LoginManager()
    login_manager.init_app(app)

    @login_manager.user_loader
    def user_loader(id):
        return User.query.get(id)

    login_manager.login_view = 'front.login'

jobplus/blueprints/__init__.py
from .home import home_bp
from .user import user_bp
from .company import company_bp
from .job import job_bp
from .firm import firm_bp
from .admin import admin_bp

jobplus/blueprints/admin.py
'''
Admin蓝图
'''

from flask import (Blueprint, render_template, flash, redirect, url_for,
                   request, current_app, abort)
from jobplus.decorators import admin_required
from jobplus.models import User, CompanyInfo, Job, db, UserInfo
from jobplus.forms import (CompanyInfoForm, EditCompanyForm, EditJobForm, 
                           AdminEditUserForm, AdminUserInfoForm, 
                           AdminCreateUserForm)


admin_bp = Blueprint('admin', __name__, url_prefix='/admin')

@admin_bp.route('/')
@admin_required
def index():
    return render_template('admin/index.html')

@admin_bp.route('/online-jobs')
@admin_required
def online_jobs():
    page = request.args.get('page', default=1, type=int)
    pagination = Job.query.filter_by(status=Job.ONLINE).paginate(
            page=page,
            per_page=current_app.config['COMPANY_PER_PAGE'],
            error_out=False
        )
    return render_template('admin/online_jobs.html', pagination=pagination)

@admin_bp.route('/offline-jobs')
@admin_required
def offline_jobs():
    page = request.args.get('page', default=1, type=int)
    pagination = Job.query.filter_by(status=Job.OFFLINE).paginate(
            page=page,
            per_page=current_app.config['COMPANY_PER_PAGE'],
            error_out=False
        )
    return render_template('admin/offline_jobs.html', pagination=pagination)

@admin_bp.route('/online/<int:job_id>', methods=['GET', 'POST'])
@admin_required
def online(job_id):
    job = Job.query.get_or_404(job_id)
    job.status = Job.ONLINE
    db.session.add(job)
    db.session.commit()
    return redirect(url_for('.offline_jobs'))

@admin_bp.route('/offline/<int:job_id>', methods=['GET', 'POST'])
@admin_required
def offline(job_id):
    job = Job.query.get_or_404(job_id)
    job.status = Job.OFFLINE
    db.session.add(job)
    db.session.commit()
    return redirect(url_for('.online_jobs'))

@admin_bp.route('/edit-job/<int:job_id>', methods=['GET', 'POST'])
@admin_required
def edit_job(job_id):
    job = Job.query.get_or_404(job_id)
    form = EditJobForm(obj=job)
    if form.validate_on_submit():
        form.update_job(job)
        flash('职位更新成功', 'success')
        return redirect(url_for('.online_jobs'))
    return render_template('admin/edit_job.html', form=form, job=job)

@admin_bp.route('/del-job/<int:job_id>', methods=['GET', 'POST'])
@admin_required
def del_job(job_id):
    job = Job.query.get_or_404(job_id)
    db.session.delete(job)
    db.session.commit()
    flash('职位已删除', 'success')
    return redirect(url_for('.online_jobs'))

@admin_bp.route('/users')
@admin_required
def users():
    page = request.args.get('page', default=1, type=int)
    pagination = User.query.filter_by(role=10).paginate(
            page=page,
            per_page=current_app.config['COMPANY_PER_PAGE'],
            error_out=False
        )
    return render_template('admin/users.html', pagination=pagination)

@admin_bp.route('/edit-user/<int:user_id>', methods=['GET', 'POST'])
@admin_required
def edit_user(user_id):
    user = User.query.get_or_404(user_id)
    form = AdminEditUserForm(obj=user)
    if form.validate_on_submit():
        form.update_user(user)
        flash('用户更新成功', 'success')
        if user.role == 10:
            return redirect(url_for('.users'))
        else:
            return redirect(url_for('.companies'))
    return render_template('admin/edit_user.html', form=form, user=user)
    
@admin_bp.route('/edit-userinfo/<int:user_id>', methods=['GET', 'POST'])
@admin_required
def edit_userinfo(user_id):
    user = User.query.get_or_404(user_id)
    if user.role == 10:
        user_info = user.user_info
        form = AdminUserInfoForm(obj=user_info)
    else:
        abort(404)
    if form.validate_on_submit():
        if user_info:
            form.update_userinfo(user_info, user)
            flash('用户信息更新成功', 'success')
            return redirect(url_for('.users'))
        else:
            user_info = UserInfo()
            form.update_userinfo(user_info, user)
            flash('用户信息更新成功', 'success')
            return redirect(url_for('.users'))
    return render_template('admin/edit_userinfo.html', form=form, user=user)

@admin_bp.route('/del-user/<int:user_id>', methods=['GET', 'POST'])
@admin_required
def del_user(user_id):
    user = User.query.get_or_404(user_id)
    role = user.role
    db.session.delete(user)
    db.session.commit()
    flash('用户已删除', 'success')
    if role == 10:
        return redirect(url_for('.users'))
    elif role == 20:
        return redirect(url_for('.companies'))
    else:
        return redirect(url_for('.users_ban'))

@admin_bp.route('/companies')
@admin_required
def companies():
    page = request.args.get('page', default=1, type=int)
    pagination = User.query.filter_by(role=20).paginate(
            page=page,
            per_page=current_app.config['COMPANY_PER_PAGE'],
            error_out=False
        )
    return render_template('admin/companies.html', pagination=pagination)

@admin_bp.route('/edit-companyinfo/<int:user_id>', methods=['GET', 'POST'])
@admin_required
def edit_companyinfo(user_id):
    user = User.query.get_or_404(user_id)
    if user.role == 20:
        company_info = user.company_info
        form = CompanyInfoForm(obj=company_info)
    else:
        abort(404)
    if form.validate_on_submit():
        if company_info:
            form.update_companyinfo(company_info)
            flash('企业信息更新成功', 'success')
            return redirect(url_for('.companies'))
        else:
            form.create_companyinfo(user)
            flash('企业信息更新成功', 'success')
            return redirect(url_for('.companies'))
    return render_template('admin/edit_companyinfo.html',
                           form=form, user=user)

@admin_bp.route('/ban/<int:user_id>', methods=['GET', 'POST'])
@admin_required
def ban(user_id):
    user = User.query.get_or_404(user_id)
    role = user.role
    if role == 20:
        user.username += 'bc'
    else:
        user.username += 'bu' 
    user.role = 0
    db.session.add(user)
    db.session.commit()
    return redirect(url_for('.users_ban'))

@admin_bp.route('/lift-ban/<int:user_id>', methods=['GET', 'POST'])
@admin_required
def lift_ban(user_id):
    user = User.query.get_or_404(user_id)
    if 'bc' in user.username:
        user.role = 20
        user.username = user.username.replace('bc', '')
    else:
        user.role = 10
        user.username = user.username.replace('bu', '')
    db.session.add(user)
    db.session.commit()
    return redirect(url_for('.users_ban'))

@admin_bp.route('/users-ban')
@admin_required
def users_ban():
    page = request.args.get('page', default=1, type=int)
    pagination = User.query.filter_by(role=0).paginate(
            page=page,
            per_page=current_app.config['COMPANY_PER_PAGE'],
            error_out=False
        )
    return render_template('admin/ban_users.html', pagination=pagination)

@admin_bp.route('/create-user', methods=['GET', 'POST'])
@admin_required
def create_user():
    form = AdminCreateUserForm()
    if form.validate_on_submit():
        form.create_user()
        flash('用户创建成功', 'success')
        return redirect(url_for('.index'))
    return render_template('admin/create_user.html', form=form)
    

jobplus/blueprints/company.py
'''
企业蓝图
'''

from flask import (Blueprint, render_template, flash, redirect, url_for,
                   request, current_app, abort, g)
from flask_login import current_user
from jobplus.decorators import company_required
from jobplus.models import User, CompanyInfo, Job, db, SendCV
from jobplus.forms import CompanyInfoForm, EditCompanyForm, PostJobForm, EditJobForm
from jobplus.libs.helper import count_unread


company_bp = Blueprint('company', __name__, url_prefix='/company')

@company_bp.route('/')
@company_required
def index():
    unread_num = count_unread() 
    return render_template('company/index.html', unread_num=unread_num)

@company_bp.route('/info')
@company_required
def company_info():
    user = User.query.filter_by(username=current_user.username).first()
    unread_num = count_unread() 
    return render_template('company/company_info.html', user=user, 
                           unread_num=unread_num)

@company_bp.route('/edit-companyinfo', methods=['GET', 'POST'])
@company_required
def edit_companyinfo():
    user = User.query.filter_by(username=current_user.username).first()
    company_info = user.company_info
    form = CompanyInfoForm(obj=company_info)
    if not company_info:
        if form.validate_on_submit():
            form.create_companyinfo(user)
            flash('信息更新成功！', 'success')
            return redirect(url_for('.company_info'))
    else:
        if form.validate_on_submit():
            form.update_companyinfo(company_info)
            flash('信息更新成功！', 'success')
            return redirect(url_for('.company_info'))
    return render_template('company/edit_companyinfo.html', form=form)

@company_bp.route('/edit-company', methods=['GET', 'POST'])
@company_required
def edit_company():
    user = User.query.filter_by(username=current_user.username).first()
    form = EditCompanyForm(obj=user)
    if form.validate_on_submit():
        form.update_user(user)
        flash('信息更新成功！', 'success')
        return redirect(url_for('.company_info'))
    return render_template('company/edit_company.html', form=form)
        
@company_bp.route('/post-job', methods=['GET', 'POST'])
@company_required
def post_job():
    form = PostJobForm()
    unread_num = count_unread() 
    if form.validate_on_submit():
        form.create_job()
        flash('职位发布成功！', 'success')
        return redirect(url_for('.online_jobs'))
    return render_template('company/post_job.html', form=form, unread_num=unread_num)

@company_bp.route('/online-jobs')
@company_required
def online_jobs():
    user = User.query.filter_by(username=current_user.username).first()
    page = request.args.get('page', default=1, type=int)
    pagination = Job.query.with_parent(user).filter_by(status=Job.ONLINE).paginate(
                page=page,
                per_page=current_app.config['COMPANY_PER_PAGE'],
                error_out=False
        )
    unread_num = count_unread() 
    return render_template('company/online_jobs.html', pagination=pagination, 
                           unread_num=unread_num)

@company_bp.route('/offline-jobs')
@company_required
def offline_jobs():
    user = User.query.filter_by(username=current_user.username).first()
    page = request.args.get('page', default=1, type=int)
    pagination = Job.query.with_parent(user).filter_by(status=Job.OFFLINE).paginate(
                page=page,
                per_page=current_app.config['COMPANY_PER_PAGE'],
                error_out=False
        )
    unread_num = count_unread() 
    return render_template('company/offline_jobs.html', pagination=pagination, 
                           unread_num=unread_num)

@company_bp.route('/online/<int:job_id>', methods=['GET', 'POST'])
@company_required
def online(job_id):
    job = Job.query.get_or_404(job_id)
    job.status = Job.ONLINE
    db.session.add(job)
    db.session.commit()
    return redirect(url_for('.offline_jobs'))

@company_bp.route('/offline/<int:job_id>', methods=['GET', 'POST'])
@company_required
def offline(job_id):
    job = Job.query.get_or_404(job_id)
    job.status = Job.OFFLINE
    db.session.add(job)
    db.session.commit()
    return redirect(url_for('.online_jobs'))

@company_bp.route('/edit-job/<int:job_id>', methods=['GET', 'POST'])
@company_required
def edit_job(job_id):
    job = Job.query.get_or_404(job_id)
    if job.company.username == current_user.username:
        form = EditJobForm(obj=job)
        if form.validate_on_submit():
            form.update_job(job)
            flash('职位更新成功', 'success')
            return redirect(url_for('.index'))
    else:
        abort(404)
    unread_num = count_unread() 
    return render_template('company/edit_job.html', form=form, job=job, 
                            unread_num=unread_num)

@company_bp.route('/del-job/<int:job_id>', methods=['GET', 'POST'])
@company_required
def del_job(job_id):
    job = Job.query.get_or_404(job_id)
    if job.company.username == current_user.username:
        db.session.delete(job)
        db.session.commit()
        flash('职位已删除', 'success')
        return redirect(url_for('.index'))
    else:
        abort(404)

@company_bp.route('/unread-cv')
@company_required
def unread_cv():
    page = request.args.get('page', default=1, type=int)
    pagination = SendCV.query.filter_by(
            receiver_id=current_user.id, status=10).paginate(
                page=page,
                per_page=current_app.config['COMPANY_PER_PAGE'],
                error_out=False
        )
    unread_num = count_unread() 
    return render_template('company/unread_cv.html', pagination=pagination, 
                            unread_num=unread_num)

@company_bp.route('/accept-cv')
@company_required
def accept_cv():
    page = request.args.get('page', default=1, type=int)
    pagination = SendCV.query.filter_by(
            receiver_id=current_user.id, status=30).paginate(
                page=page,
                per_page=current_app.config['COMPANY_PER_PAGE'],
                error_out=False
        )
    unread_num = count_unread() 
    return render_template('company/accept_cv.html', pagination=pagination,  
                            unread_num=unread_num)

@company_bp.route('/refuse-cv')
@company_required
def refuse_cv():
    page = request.args.get('page', default=1, type=int)
    pagination = SendCV.query.filter_by(
            receiver_id=current_user.id, status=20).paginate(
                page=page,
                per_page=current_app.config['COMPANY_PER_PAGE'],
                error_out=False
        )
    unread_num = count_unread() 
    return render_template('company/refuse_cv.html', pagination=pagination, 
                            unread_num=unread_num)

@company_bp.route('/refuse/<int:job_id>/<int:user_id>', methods=['GET', 'POST'])
@company_required
def refuse(job_id, user_id):
    send_cv = SendCV.query.filter_by(job_id=job_id, sender_id=user_id).first_or_404()
    send_cv.status = 20
    db.session.add(send_cv)
    db.session.commit()
    return redirect(url_for('.unread_cv'))

@company_bp.route('/accept/<int:job_id>/<int:user_id>', methods=['GET', 'POST'])
@company_required
def accept(job_id, user_id):
    send_cv = SendCV.query.filter_by(job_id=job_id, sender_id=user_id).first_or_404()
    send_cv.status = 30
    db.session.add(send_cv)
    db.session.commit()
    flash('已接受该简历，快去联系求职者面试吧！', 'success')
    return redirect(url_for('.accept_cv'))

jobplus/blueprints/job.py
'''
Job蓝图
'''

from flask import (Blueprint, render_template, flash, redirect, url_for,
                   request, current_app)
from jobplus.models import Job, SendCV, User
from flask_login import current_user
from jobplus.forms import *


job_bp = Blueprint('job', __name__, url_prefix='/jobs')

@job_bp.route('/')
def jobs():
    page = request.args.get('page', default=1, type=int)
    pagination = Job.query.filter_by(status=Job.ONLINE).paginate(
            page=page,
            per_page=current_app.config['HOME_PER_PAGE'],
            error_out=False
        )
    return render_template('jobs/jobs.html', pagination=pagination)

@job_bp.route('/<int:job_id>')
def job_detail(job_id):
    #job = Job.query.get_or_404(job_id)
    job = Job.query.filter_by(id=job_id, status=Job.ONLINE).first_or_404()
    sendcv = SendCV()
    if current_user.is_authenticated:
        user = User.query.filter_by(id=current_user.id).first()
        return render_template('jobs/detail.html', job=job, 
                                sendcv=sendcv, user=user)
    else:
        return render_template('jobs/detail.html', job=job)

jobplus/blueprints/resume.py
from flask import Blueprint, render_template, flash, redirect, url_for
from flask_login import current_user
from jobplus.models import Resume, User


resume_bp = Blueprint('resume', __name__, url_prefix='/resume')

@resume_bp.route('/send-resume')
def send_resume()

jobplus/templates/company/accept_cv.html
{% extends "company/index.html" %}
{% from "macros.html" import render_pagination %}

{% block title %}Accept-CV{% endblock %}

{% block company %}
<table class="table">
  <thead>
    <tr>
      <th>职位</th>
      <th>求职者</th>
      <th>简历</th>
      <th>电话</th>
    </tr>
    <tbody>
      {% for cv in pagination.items %}
      <tr>
        <td>{{ cv.job.title }}</td>
        <td>{{ cv.sender.user_info.name }}</td>
        <td>{{ cv.sender.user_info.resume }}</td>
        <td>{{ cv.sender.user_info.phone_number }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </thead>
</table>
{{ render_pagination(pagination, 'company.received_cv') }}
{% endblock %}

jobplus/templates/company/index.html
{% extends "base.html" %}

{% block title %}CompanyPage{% endblock %}

{% block body %}
<div class="row">
  <div class="col-md-3">
    <h4>管理</h4>
    <div class="list-group">
      <a href="{{ url_for('company.company_info') }}" 
         class="list-group-item list-group-item-action list-group-item-light">
         企业信息</a>
      <a href="{{ url_for('company.online_jobs') }}" 
         class="list-group-item list-group-item-action list-group-item-light">
         已发职位</a>
      <a href="{{ url_for('company.unread_cv') }}" 
         class="list-group-item list-group-item-action list-group-item-light">
         未读简历：{{ unread_num }}</a>
      <a href="{{ url_for('company.accept_cv') }}" 
         class="list-group-item list-group-item-action list-group-item-light">
         已接受简历</a>
      <a href="{{ url_for('company.refuse_cv') }}" 
         class="list-group-item list-group-item-action list-group-item-light">
         已拒绝简历</a>
    </div>
    <br>
    <a href="{{ url_for('company.post_job') }}" type="button" class="btn btn-outline-dark">
      <span class="glyphicon glyphicon" aria-hidden="true"></span>
      发布职位
    </a>
</div>
<div class="col-md-9">
  {% block company %}{% endblock %}
</div>
{% endblock %}

jobplus/templates/company/offline_jobs.html
{% extends "company/index.html" %}
{% from "macros.html" import render_pagination %}

{% block title %}Company-OfflineJobs{% endblock %}

{% block company %}
<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link" href="{{ url_for('company.online_jobs') }}">在线职位</a>
  </li>
  <li class="nav-item">
    <a class="nav-link active" href="#">下线职位</a>
  </li>
</ul>
<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>职位</th>
      <th>薪资</th>
      <th>经验</th>
      <th>学历</th>
      <th>标签</th>
      <th>操作</th>
    </tr>
    <tbody>
      {% for job in pagination.items %}
      <tr>
        <td>{{ job.id }}</td>
        <td>{{ job.title }}</td>
        <td>{{ job.salary_lower }}k-{{ job.salary_upper }}k</td>
        <td>{{ job.experience_lower}}-{{ job.experience_upper }}</td>
        <td>{{ job.education }}</td>
        <td>{{ job.tags }}</td>
        <td>
          <div class="btn-group">
            <button class="btn btn-secondary btn-sm dropdown-toggle" 
                    type="button" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
               操作
            </button>

            <div class="dropdown-menu">
               <a class="dropdown-item" 
                  href="{{ url_for('company.edit_job', job_id=job.id) }}">编辑</a>
               <a class="dropdown-item" 
                  href="{{ url_for('company.online', job_id=job.id) }}">上线</a>
               <a class="dropdown-item" 
                  href="{{ url_for('company.del_job', job_id=job.id) }}">删除</a>
            </div>
          </div>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </thead>
</table>
{{ render_pagination(pagination, 'company.offline_jobs') }}
{% endblock %}

jobplus/templates/company/online_jobs.html
{% extends "company/index.html" %}
{% from "macros.html" import render_pagination %}

{% block title %}Company-OnlineJobs{% endblock %}

{% block company %}
<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link active" href="#">在线职位</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{{ url_for('company.offline_jobs') }}">下线职位</a>
  </li>
</ul>
<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>职位</th>
      <th>薪资</th>
      <th>经验</th>
      <th>学历</th>
      <th>标签</th>
      <th>操作</th>
    </tr>
    <tbody>
      {% for job in pagination.items %}
      <tr>
        <td>{{ job.id }}</td>
        <td>{{ job.title }}</td>
        <td>{{ job.salary_lower }}k-{{ job.salary_upper }}k</td>
        <td>{{ job.experience_lower}}-{{ job.experience_upper }}</td>
        <td>{{ job.education }}</td>
        <td>{{ job.tags }}</td>
        <td>
          <div class="btn-group">
            <button class="btn btn-secondary btn-sm dropdown-toggle" 
                    type="button" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
               操作
            </button>

            <div class="dropdown-menu">
               <a class="dropdown-item" 
                  href="{{ url_for('job.job_detail', job_id=job.id) }}">查看</a>
               <a class="dropdown-item" 
                  href="{{ url_for('company.edit_job', job_id=job.id) }}">编辑</a>
               <a class="dropdown-item" 
                  href="{{ url_for('company.offline', job_id=job.id) }}">下线</a>
               <a class="dropdown-item" 
                  href="{{ url_for('company.del_job', job_id=job.id) }}">删除</a>
            </div>
          </div>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </thead>
</table>
{{ render_pagination(pagination, 'company.online_jobs') }}
{% endblock %}

jobplus/templates/company/refuse_cv.html
{% extends "company/index.html" %}
{% from "macros.html" import render_pagination %}

{% block title %}Refuce-CV{% endblock %}

{% block company %}
<table class="table">
  <thead>
    <tr>
      <th>职位</th>
      <th>求职者</th>
      <th>简历</th>
      <th>操作</th>
    </tr>
    <tbody>
      {% for cv in pagination.items %}
      <tr>
        <td>{{ cv.job.title }}</td>
        <td>{{ cv.sender.user_info.name }}</td>
        <td>{{ cv.sender.user_info.resume }}</td>
        <td>
          <div class="btn-group">
            <button class="btn btn-secondary btn-sm dropdown-toggle" 
                    type="button" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
               操作
            </button>

            <div class="dropdown-menu">
               <a class="dropdown-item" 
                  href="{{ url_for('company.accept', job_id=cv.job.id,
                           user_id=cv.sender.id) }}">同意</a>
            </div>
          </div>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </thead>
</table>
{{ render_pagination(pagination, 'company.refuce_cv') }}
{% endblock %}

jobplus/templates/company/unread_cv.html
{% extends "company/index.html" %}
{% from "macros.html" import render_pagination %}

{% block title %}Unread-CV{% endblock %}

{% block company %}
<table class="table">
  <thead>
    <tr>
      <th>职位</th>
      <th>求职者</th>
      <th>简历</th>
      <th>操作</th>
    </tr>
    <tbody>
      {% for cv in pagination.items %}
      <tr>
        <td>{{ cv.job.title }}</td>
        <td>{{ cv.sender.user_info.name }}</td>
        <td>{{ cv.sender.user_info.resume }}</td>
        <td>
          <div class="btn-group">
            <button class="btn btn-secondary btn-sm dropdown-toggle" 
                    type="button" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
               操作
            </button>

            <div class="dropdown-menu">
               <a class="dropdown-item" 
                  href="{{ url_for('company.refuse', job_id=cv.job.id, 
                           user_id=cv.sender.id) }}">拒绝</a>
               <a class="dropdown-item" 
                  href="{{ url_for('company.accept', job_id=cv.job.id,
                           user_id=cv.sender.id) }}">同意</a>
            </div>
          </div>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </thead>
</table>
{{ render_pagination(pagination, 'company.received_cv') }}
{% endblock %}