jobplus/app.py
'''
注册蓝图、初始化数据库、定义 create_app 函数
'''

from flask import Flask
from flask_migrate import Migrate
from flask_login import LoginManager
from jobplus.config import configs
from jobplus.models import db, User
from jobplus.blueprints import (home_bp, user_bp, company_bp, job_bp, 
                                firm_bp, admin_bp)


def create_app(config):
    app = Flask(__name__)
    app.config.from_object(configs.get(config))
    register_blueprints(app)
    register_extensions(app)
    return app


def register_blueprints(app):
    app.register_blueprint(home_bp)
    app.register_blueprint(user_bp)
    app.register_blueprint(company_bp)
    app.register_blueprint(job_bp)
    app.register_blueprint(firm_bp)
    app.register_blueprint(admin_bp)


def register_extensions(app):
    db.init_app(app)
    Migrate(app, db)
    login_manager = LoginManager()
    login_manager.init_app(app)

    @login_manager.user_loader
    def user_loader(id):
        return User.query.get(id)

    login_manager.login_view = 'front.login'

jobplus/blueprints/__init__.py
from .home import home_bp
from .user import user_bp
from .company import company_bp
from .job import job_bp
from .firm import firm_bp
from .admin import admin_bp

jobplus/blueprints/admin.py
'''
Admin蓝图
'''

from flask import (Blueprint, render_template, flash, redirect, url_for,
                   request, current_app, abort)
from jobplus.decorators import admin_required
from jobplus.models import User, CompanyInfo, Job, db, UserInfo
from jobplus.forms import (CompanyInfoForm, EditCompanyForm, EditJobForm, 
                           AdminEditUserForm, AdminUserInfoForm, 
                           AdminCreateUserForm)


admin_bp = Blueprint('admin', __name__, url_prefix='/admin')

@admin_bp.route('/')
@admin_required
def index():
    return render_template('admin/index.html')

@admin_bp.route('/online-jobs')
@admin_required
def online_jobs():
    page = request.args.get('page', default=1, type=int)
    pagination = Job.query.filter_by(status=Job.ONLINE).paginate(
            page=page,
            per_page=current_app.config['COMPANY_PER_PAGE'],
            error_out=False
        )
    return render_template('admin/online_jobs.html', pagination=pagination)

@admin_bp.route('/offline-jobs')
@admin_required
def offline_jobs():
    page = request.args.get('page', default=1, type=int)
    pagination = Job.query.filter_by(status=Job.OFFLINE).paginate(
            page=page,
            per_page=current_app.config['COMPANY_PER_PAGE'],
            error_out=False
        )
    return render_template('admin/offline_jobs.html', pagination=pagination)

@admin_bp.route('/online/<int:job_id>', methods=['GET', 'POST'])
@admin_required
def online(job_id):
    job = Job.query.get_or_404(job_id)
    job.status = Job.ONLINE
    db.session.add(job)
    db.session.commit()
    return redirect(url_for('.offline_jobs'))

@admin_bp.route('/offline/<int:job_id>', methods=['GET', 'POST'])
@admin_required
def offline(job_id):
    job = Job.query.get_or_404(job_id)
    job.status = Job.OFFLINE
    db.session.add(job)
    db.session.commit()
    return redirect(url_for('.online_jobs'))

@admin_bp.route('/edit-job/<int:job_id>', methods=['GET', 'POST'])
@admin_required
def edit_job(job_id):
    job = Job.query.get_or_404(job_id)
    form = EditJobForm(obj=job)
    if form.validate_on_submit():
        form.update_job(job)
        flash('职位更新成功', 'success')
        return redirect(url_for('.online_jobs'))
    return render_template('admin/edit_job.html', form=form, job=job)

@admin_bp.route('/del-job/<int:job_id>', methods=['GET', 'POST'])
@admin_required
def del_job(job_id):
    job = Job.query.get_or_404(job_id)
    db.session.delete(job)
    db.session.commit()
    flash('职位已删除', 'success')
    return redirect(url_for('.online_jobs'))

@admin_bp.route('/users')
@admin_required
def users():
    page = request.args.get('page', default=1, type=int)
    pagination = User.query.filter_by(role=10).paginate(
            page=page,
            per_page=current_app.config['COMPANY_PER_PAGE'],
            error_out=False
        )
    return render_template('admin/users.html', pagination=pagination)

@admin_bp.route('/edit-user/<int:user_id>', methods=['GET', 'POST'])
@admin_required
def edit_user(user_id):
    user = User.query.get_or_404(user_id)
    form = AdminEditUserForm(obj=user)
    if form.validate_on_submit():
        form.update_user(user)
        flash('用户更新成功', 'success')
        if user.role == 10:
            return redirect(url_for('.users'))
        else:
            return redirect(url_for('.companies'))
    return render_template('admin/edit_user.html', form=form, user=user)
    
@admin_bp.route('/edit-userinfo/<int:user_id>', methods=['GET', 'POST'])
@admin_required
def edit_userinfo(user_id):
    user = User.query.get_or_404(user_id)
    if user.role == 10:
        user_info = user.user_info
        form = AdminUserInfoForm(obj=user_info)
    else:
        abort(404)
    if form.validate_on_submit():
        if user_info:
            form.update_userinfo(user_info, user)
            flash('用户信息更新成功', 'success')
            return redirect(url_for('.users'))
        else:
            user_info = UserInfo()
            form.update_userinfo(user_info, user)
            flash('用户信息更新成功', 'success')
            return redirect(url_for('.users'))
    return render_template('admin/edit_userinfo.html', form=form, user=user)

@admin_bp.route('/del-user/<int:user_id>', methods=['GET', 'POST'])
@admin_required
def del_user(user_id):
    user = User.query.get_or_404(user_id)
    role = user.role
    db.session.delete(user)
    db.session.commit()
    flash('用户已删除', 'success')
    if role == 10:
        return redirect(url_for('.users'))
    elif role == 20:
        return redirect(url_for('.companies'))
    else:
        return redirect(url_for('.users_ban'))

@admin_bp.route('/companies')
@admin_required
def companies():
    page = request.args.get('page', default=1, type=int)
    pagination = User.query.filter_by(role=20).paginate(
            page=page,
            per_page=current_app.config['COMPANY_PER_PAGE'],
            error_out=False
        )
    return render_template('admin/companies.html', pagination=pagination)

@admin_bp.route('/edit-companyinfo/<int:user_id>', methods=['GET', 'POST'])
@admin_required
def edit_companyinfo(user_id):
    user = User.query.get_or_404(user_id)
    if user.role == 20:
        company_info = user.company_info
        form = CompanyInfoForm(obj=company_info)
    else:
        abort(404)
    if form.validate_on_submit():
        if company_info:
            form.update_companyinfo(company_info)
            flash('企业信息更新成功', 'success')
            return redirect(url_for('.companies'))
        else:
            form.create_companyinfo(user)
            flash('企业信息更新成功', 'success')
            return redirect(url_for('.companies'))
    return render_template('admin/edit_companyinfo.html',
                           form=form, user=user)

@admin_bp.route('/ban/<int:user_id>', methods=['GET', 'POST'])
@admin_required
def ban(user_id):
    user = User.query.get_or_404(user_id)
    role = user.role
    if role == 20:
        user.username += 'bc'
    else:
        user.username += 'bu' 
    user.role = 0
    db.session.add(user)
    db.session.commit()
    return redirect(url_for('.users_ban'))

@admin_bp.route('/lift-ban/<int:user_id>', methods=['GET', 'POST'])
@admin_required
def lift_ban(user_id):
    user = User.query.get_or_404(user_id)
    if 'bc' in user.username:
        user.role = 20
        user.username = user.username.replace('bc', '')
    else:
        user.role = 10
        user.username = user.username.replace('bu', '')
    db.session.add(user)
    db.session.commit()
    return redirect(url_for('.users_ban'))

@admin_bp.route('/users-ban')
@admin_required
def users_ban():
    page = request.args.get('page', default=1, type=int)
    pagination = User.query.filter_by(role=0).paginate(
            page=page,
            per_page=current_app.config['COMPANY_PER_PAGE'],
            error_out=False
        )
    return render_template('admin/ban_users.html', pagination=pagination)

@admin_bp.route('/create-user', methods=['GET', 'POST'])
@admin_required
def create_user():
    form = AdminCreateUserForm()
    if form.validate_on_submit():
        form.create_user()
        flash('用户创建成功', 'success')
        return redirect(url_for('.index'))
    return render_template('admin/create_user.html', form=form)
    

jobplus/blueprints/firm.py
'''
Firm蓝图
'''

from flask import (Blueprint, render_template, flash, redirect, url_for,
                   request, current_app, abort)
from jobplus.models import Job, User


firm_bp = Blueprint('firm', __name__, url_prefix='/firms')

@firm_bp.route('/')
def firms():
    page = request.args.get('page', default=1, type=int)
    pagination = User.query.filter_by(role=20).paginate(
            page=page,
            per_page=current_app.config['HOME_PER_PAGE'],
            error_out=False
        )
    return render_template('firms/firms.html', pagination=pagination)

@firm_bp.route('/<int:user_id>')
def detail(user_id):
    firm = User.query.get_or_404(user_id)
    if firm.role != 20:
        abort(404)
    else:
        jobs_num = len(Job.query.filter_by(company_id=firm.id, 
            status=Job.ONLINE).all())
        return render_template('firms/detail.html', firm=firm, jobs_num=jobs_num)

@firm_bp.route('/<int:user_id>/jobs')
def jobs(user_id):
    firm = User.query.get_or_404(user_id)
    if firm.role != 20:
        abort(404)
    else:
        jobs = Job.query.filter_by(company_id=firm.id, status=Job.ONLINE).all()
        return render_template('firms/jobs.html', jobs=jobs, firm=firm)

jobplus/blueprints/home.py
'''
首页蓝图
'''

from flask import (Blueprint, render_template, flash, redirect, url_for,
                   abort)
from flask_login import login_user, logout_user, login_required
from jobplus.models import User, Job, db
from jobplus.forms import LoginForm, UserRegisterForm, CompanyRegisterForm

home_bp = Blueprint('home', __name__)

@home_bp.route('/')
def index():
    jobs = db.session.query(Job).order_by(Job.create_at.desc()).limit(15).all()
    return render_template('index.html', jobs=jobs)

@home_bp.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user.role == 0:
            abort(403)
        else:
            login_user(user, form.remember_me.data)
            return redirect(url_for('.index'))
    '''
    else:
        flash('您的帐户已被封禁', 'danger')
        return redirect(url_for('.login'))
    '''    
    return render_template('login.html', form=form)

@home_bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash('您已退出登录', 'success')
    return redirect(url_for('.index'))

@home_bp.route('/user-register', methods=['GET', 'POST'])
def user_register():
    form = UserRegisterForm()
    if form.validate_on_submit():
        form.create_user()
        flash('注册成功，请登录！', 'success')
        return redirect(url_for('.login'))
    return render_template('user_register.html', form=form)

@home_bp.route('/company-register', methods=['GET', 'POST'])
def company_register():
    form = CompanyRegisterForm()
    if form.validate_on_submit():
        form.create_company()
        flash('注册成功，请登录！', 'success')
        return redirect(url_for('.login'))
    return render_template('company_register.html', form=form)
   

jobplus/blueprints/job.py
'''
Job蓝图
'''

from flask import (Blueprint, render_template, flash, redirect, url_for,
                   request, current_app)
from jobplus.models import Job, SendCV, User
from flask_login import current_user
from jobplus.forms import *


job_bp = Blueprint('job', __name__, url_prefix='/jobs')

@job_bp.route('/')
def jobs():
    page = request.args.get('page', default=1, type=int)
    pagination = Job.query.filter_by(status=Job.ONLINE).paginate(
            page=page,
            per_page=current_app.config['HOME_PER_PAGE'],
            error_out=False
        )
    return render_template('jobs/jobs.html', pagination=pagination)

@job_bp.route('/<int:job_id>')
def job_detail(job_id):
    #job = Job.query.get_or_404(job_id)
    job = Job.query.filter_by(id=job_id, status=Job.ONLINE).first_or_404()
    sendcv = SendCV()
    if current_user.is_authenticated:
        user = User.query.filter_by(id=current_user.id).first()
        return render_template('jobs/detail.html', job=job, 
                                sendcv=sendcv, user=user)
    else:
        return render_template('jobs/detail.html', job=job)

jobplus/blueprints/resume.py
from flask import Blueprint, render_template, flash, redirect, url_for
from flask_login import current_user
from jobplus.models import Resume, User


resume_bp = Blueprint('resume', __name__, url_prefix='/resume')

@resume_bp.route('/send-resume')
def send_resume()

jobplus/blueprints/user.py
'''
用户蓝图
'''

from flask import (Blueprint, render_template, flash, redirect, 
                   url_for, abort, request, current_app)
from flask_login import current_user
from jobplus.decorators import user_required
from jobplus.models import User, UserInfo, SendCV, Job, db
from jobplus.forms import UserInfoForm, EditUserForm


user_bp = Blueprint('user', __name__, url_prefix='/user')

@user_bp.route('/')
@user_required
def index():
    return render_template('user/index.html')

@user_bp.route('/info')
@user_required
def userinfo():
    user = User.query.filter_by(username=current_user.username).first()
    return render_template('user/user_info.html', user=user)

@user_bp.route('/edit-userinfo', methods=['GET', 'POST'])
@user_required
def edit_userinfo():
    user = User.query.filter_by(username=current_user.username).first()
    user_info = user.user_info
    form = UserInfoForm(obj=user_info)
    if not user_info:
        if form.validate_on_submit():
            form.create_userinfo(user)
            flash('信息更新成功！', 'success')
            return redirect(url_for('.index'))
    else:
        if form.validate_on_submit():
            form.update_userinfo(user_info)
            flash('信息更新成功！', 'success')
            return redirect(url_for('.index'))
    return render_template('user/edit_userinfo.html', form=form)

@user_bp.route('/edit-user', methods=['GET', 'POST'])
@user_required
def edit_user():
    user = User.query.filter_by(username=current_user.username).first()
    form = EditUserForm(obj=user)
    if form.validate_on_submit():
        form.update_user(user)
        flash('信息更新成功！', 'success')
        return redirect(url_for('.index'))
    return render_template('user/edit_user.html', form=form)
        
@user_bp.route('/send-cv/<int:job_id>/<int:company_id>', methods=['GET', 'POST'])
@user_required
def send_cv(job_id, company_id):
    job = Job.query.filter_by(id=job_id).first_or_404()
    user = User.query.filter_by(username=current_user.username).first()
    company = User.query.filter_by(id=company_id).first()
    send_cv = SendCV() 
    send_cv.sender = user
    send_cv.job = job
    send_cv.receiver = company
    db.session.add(send_cv)
    db.session.commit()
    flash('简历投递成功！', 'success')
    return redirect(url_for('job.job_detail', job_id=job.id))
    
@user_bp.route('/sent-cv')
@user_required
def sent_cv():
    page = request.args.get('page', default=1, type=int)
    pagination = SendCV.query.filter_by(
            sender_id=current_user.id).paginate(
                page=page,
                per_page=current_app.config['COMPANY_PER_PAGE'],
                error_out=False
        )
    return render_template('user/sent_cv.html', 
            pagination=pagination)

@user_bp.route('/del-cv/<int:job_id>', methods=['GET', 'POST'])
@user_required
def del_cv(job_id):
    send_cv = SendCV.query.filter_by(job_id=job_id, 
            sender_id=current_user.id).first_or_404()
    db.session.delete(send_cv)
    db.session.commit()
    return redirect(url_for('.sent_cv'))

@user_bp.route('/unread-cv')
@user_required
def unread_cv():
    page = request.args.get('page', default=1, type=int)
    pagination = SendCV.query.filter_by(
            sender_id=current_user.id, status=10).paginate(
                page=page,
                per_page=current_app.config['COMPANY_PER_PAGE'],
                error_out=False
        )
    return render_template('user/unread_cv.html', 
            pagination=pagination)

@user_bp.route('/accept-cv')
@user_required
def accept_cv():
    page = request.args.get('page', default=1, type=int)
    pagination = SendCV.query.filter_by(
            sender_id=current_user.id, status=30).paginate(
                page=page,
                per_page=current_app.config['COMPANY_PER_PAGE'],
                error_out=False
        )
    return render_template('user/accept_cv.html', 
            pagination=pagination)

@user_bp.route('/refuse-cv')
@user_required
def refuse_cv():
    page = request.args.get('page', default=1, type=int)
    pagination = SendCV.query.filter_by(
            sender_id=current_user.id, status=20).paginate(
                page=page,
                per_page=current_app.config['COMPANY_PER_PAGE'],
                error_out=False
        )
    return render_template('user/refuse_cv.html', 
            pagination=pagination)

jobplus/templates/firms/detail.html
{% extends "base.html" %}

{% block title %}Company-Detail{% endblock %}

{% block body %}
<div class="jumbotron jumbotron-fluid">
  <div class="row">
    <div class="col-md-8">
      <div class="container">
        <h1 class="display-4">{{ firm.username }}</h1>
        <h4>{{ firm.company_info.intro }}</h4>
        <br>
        <p class="lead">关于这个公司, 你想知道的都在这里</p>
      </div>
    </div>
    <div class="col-md-4">
      <div class="media">
        <img src="{{ firm.company_info.logo }}" class="mr-3" width="160" height="160" alt="{{ firm.username }}">
      </div>
    </div>
  </div>
</div>
<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link active" href="#">企业详情</a>
  </li>
  <li class="nav-item" >
  <a class="nav-link" href="{{ url_for('firm.jobs', user_id=firm.id) }}">
                               在招职位: {{ jobs_num }}</a>
  </li>
</ul>
<div class="row">
  <div class="col-md-8">
    <br>
    <h4>业务领域</h4>
    {% if firm.company_info.domain %}
    {% for domain in firm.company_info.domain.split() %}
    <span class="badge badge-pill badge-info">{{ domain }}</span>
    {% endfor %}
    {% else %}
    <span class="badge badge-pill badge-info">暂无</span>
    {% endif %}
    <br>
    <br>
    <h4>企业介绍</h4>
    <p>{{ firm.company_info.detail }}</p>
  </div>
  <div class="col-md-4">
    <br>
    <center>
    <h4>企业基本信息</h4>
    <a href="{{ firm.company_info.website }}">
      <p>官方网站</p>
    </a>
    <p>所在城市: {{  firm.company_info.address }}</p>
    </center>
  </div>
</div>
{% endblock %}

jobplus/templates/firms/firms.html
{% extends "base.html" %}
{% from "macros.html" import render_pagination %}

{% block title %}Jobs{% endblock %}

{% block body%}
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">JOBPLUS</h1>
    <p class="lead">他们都在这里等着你, 也有可能是别人</p>
  </div>
</div>
<div class="card-columns">
  {% for company in pagination.items %}
    <div class="card bg-light mb-3" style="max-width: 18rem;">
      <div class="card-body">
        <div class="media">
            <a href="{{ url_for('firm.detail', user_id=company.id) }}">
            <img src="{{ company.company_info.logo }}" class="mr-3" width="64" height="64" alt="{{ company.username }}">
            <div class="media-body">
              <p class="mt-0">{{ company.username }}</p>
          </a>
              <p class="mt-0">
              {{ company.company_info.address }}
                <a href="{{ company.company_info.website }}">
              企业官网</p>
                </a>
            </div>
        </div>
        {% if company.company_info.domain %}
        {% for domain in company.company_info.domain.split() %}
          <span class="badge badge-pill badge-info">{{ domain }}</span>
        {% endfor %}
        {% else %}
          <span class="badge badge-pill badge-info">暂无</span>
        {% endif %}
      </div>
        <div class="card-footer">
          <center>
            <p>{{ company.company_info.intro }}</p>
            <p>再招职位：
            <a href="{{ url_for('firm.jobs', user_id=company.id) }}">
            {{ company.publish_job|length }}</p>
            </a>
          </center>
        </div>
    </div>
  {% endfor %}
</div>
{{ render_pagination(pagination, 'firm.firms') }}
{% endblock %}

jobplus/templates/firms/jobs.html
{% extends "base.html" %}

{% block title %}Company-Detail{% endblock %}

{% block body %}
<div class="jumbotron jumbotron-fluid">
  <div class="row">
    <div class="col-md-8">
      <div class="container">
        <h1 class="display-4">{{ firm.username }}</h1>
        <h4>{{ firm.company_info.intro }}</h4>
        <br>
        <p class="lead">关于这个公司, 你想知道的都在这里</p>
      </div>
    </div>
    <div class="col-md-4">
      <div class="media">
        <img src="{{ firm.company_info.logo }}" class="mr-3" width="160" height="160" alt="{{ firm.username }}">
      </div>
    </div>
  </div>
</div>
<ul class="nav nav-tabs">
  <li class="nav-item">
  <a class="nav-link" href="{{ url_for('firm.detail', user_id=firm.id) }}">企业详情</a>
  </li>
  <li class="nav-item" >
    <a class="nav-link active" href="#">在招职位: {{ jobs|length }}</a>
  </li>
</ul>
<div class="row">
  <div class="col-md-8">
    <br>
    <div class="list-group">
      {% for job in jobs %}
      <a href="{{ url_for('job.job_detail', job_id=job.id) }}" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1">{{ job.title  }}</h5>
          <small class="text-muted">{{ job.create_at }}</small>
        </div>
        <p class="mb-1">{{ job.salary_lower }}k-{{ job.salary_upper }}k
                        {% if job.experience_lower == 0 %}
                        经验不限 /
                        {% else %}
                        {{ job.experience_lower }}-{{ job.experience_upper }}年 /
                        {% endif %}
                        {{ job.education }}
        </p>
      </a>
      {% endfor %}
    </div>
  </div>
  <div class="col-md-4">
    <br>
    <center>
    <h4>企业基本信息</h4>
    <a href="{{ firm.company_info.website }}">
      <p>官方网站</p>
    </a>
    <p>所在城市: {{  firm.company_info.address }}</p>
    </center>
  </div>
</div>
{% endblock %}